// <auto-generated />
using ASP.NET_Core_Identity_Tutorial.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASP.NET_Core_Identity_Tutorial.Migrations
{
    [DbContext(typeof(ASPNET_Core_Identity_TutorialContext))]
    partial class ASPNET_Core_Identity_TutorialContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ASP.NET_Core_Identity_Tutorial.Models.Employee", b =>
                {
                    b.Property<string>("BID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BID");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
